version: "3"

services:
  springelastic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-service
    ports:
      - "8080:8080"
    environment:
      - db_host=db
      - db_name=search-service
      - username=postgres
      - password=admin
      - db_port=5432
      - es_port=elastic:9200
    depends_on:
      - db
      - elastic
  db:
    image: postgres:10-alpine
    container_name: search-service-db
    environment:
      - POSTGRES_DB=search-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
    ports:
    - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    environment:
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - "5601:5601"
    depends_on:
      - elastic