version: "3"
services:
  springelastic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-service
    ports:
      - "8080:8080"
    environment:
      - db_host=db
      - db_name=search-service
      - username=postgres
      - password=admin
      - db_port=5432
      - spring.profiles.active=psql
    depends_on:
      - postgres
  postgres:
    image: postgres:10-alpine
    container_name: search-service-db
    environment:
      - POSTGRES_DB=search-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  elastic:
    image: elasticsearch:6.5.0
    container_name: elastic-search